### ISSUE TITLE
Premaure client timeout despite configuration

### ISSUE THREAD

**Issue by psycofdj** [orange-cloudfoundry/bosh-cpi-cloudstack#4]
Got several timeout while creating a VM with a vip. 

Despite the fact that cloudstasck should not be be that long to perform the task, I'm surprised that the timeout occurs before the `1800` seconds given in the cpi config.

### CPI Error

>   Task 46 | 09:51:16 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'Could not create vips: Error when creating vip 10.234.244.63: Get https://mydomain.com/client/api?apiKey=key&command=enableStaticNat&ipaddressid=4f4139e0-fd8c-4df9-94ea-e3f21fe49db7&networkid=b749f208-e0a8-42a7-93a7-fd471ddc655a&response=json&virtualmachineid=ca5c1a97-cf9c-49f9-8f7e-f3e818f7167b&signature=sig%3D: net/http: request canceled (Client.Timeout exceeded while awaiting headers)' in 'create_vm' CPI method

### Overall task duration

>   Task 46 Duration 00:09:54

### CPI configuration

```
{
   "CloudStack" : {
       "Timeout" : {
         "DeleteVolume" : 1800,
         "AttachVolume" : 36000,
         "StopVm" : 1800,
         "CreateVm" : 1800,
         "ResizeVolume" : 1800,
         "DeleteVm" : 1800,
         "PollTemplate" : 1800,
         "DeleteSnapshotVolume" : 1800,
         "Global" : 1800,
         "SnapshotVolume" : 1800,
         "CreateVolume" : 1800,
         "RebootVm" : 1800,
         "DetachVolume" : 1800
      },
     ...
}
```

### Analysis

After reading a bit of code, it seems that:

- `enableStaticNat` is a synchroneous job in cloudstack (at least xanzy/go-cloudstack is not waiting for an AsyncJobResult in [xanzy/go-cloudstack: NATService.go](https://github.com/orange-cloudfoundry/bosh-cpi-cloudstack/blob/master/vendor/github.com/xanzy/go-cloudstack/cloudstack/NATService.go#L390-L402)
- therefore a static timeout value is used instead of AsyncTimeout in [xanzy/go-cloudstack: cloudstack.go](https://github.com/orange-cloudfoundry/bosh-cpi-cloudstack/blob/master/vendor/github.com/xanzy/go-cloudstack/cloudstack/cloudstack.go#L164-L180)
- therefore cpi's timeout configuration as no effect for this particular operation in [orange-cloudfoundry/bosh-cpi-cloudstack: create_vm.go](https://github.com/orange-cloudfoundry/bosh-cpi-cloudstack/blob/master/action/create_vm.go#L24)

**Comment by ArthurHlt** [comment]
Timeout has been set with a longer time but it seems that timeout from cloudstack is occurring too.

Now we have this kind of message when creating vip:
`invalid character '<' looking for beginning of value` 

This is an xml response from cloudstack, static nat has some issue when 2 vm are asking for nat routing in same time.

Commit https://github.com/orange-cloudfoundry/bosh-cpi-cloudstack/commit/59ed088630548afec3c31c9471ebf3bab50a9684 will now retry when it has those kind of message.
